name: Calculator Application

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set environment variables
      run: |
        echo "API_KEY=your_api_key" >> $GITHUB_ENV
        echo "OTHER_VARIABLE=value" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        pytest
